export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <h1>***sub Layout Header***</h1>
      {children}
      <h1>***sub Layout footer***</h1>
    </div>
  );
}
