export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1>===About Page Layout===</h1>

        <main>{children}</main>
      </body>
    </html>
  );
}
